# Generated by Django 4.2.4 on 2023-09-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("patient_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("telephone", models.CharField(max_length=50)),
                ("date", models.DateField(auto_now_add=True)),
                ("department", models.CharField(max_length=100)),
                ("doctor_name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "Appointments",
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=100)),
                ("subject", models.CharField(max_length=100)),
                ("message", models.TextField(max_length=500)),
            ],
            options={
                "verbose_name_plural": "Contact",
            },
        ),
        migrations.CreateModel(
            name="Dept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("dept_name", models.CharField(max_length=100)),
                ("description", models.TextField(max_length=500)),
                ("dept_image", models.ImageField(upload_to="uploads")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("hos_name", models.CharField(max_length=50)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
