# Generated by Django 4.2.4 on 2023-09-30 14:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0002_registration"),
    ]

    operations = [
        migrations.RenameField(
            model_name="registration",
            old_name="phone_name",
            new_name="phone_number",
        ),
    ]
