# Generated by Django 4.2.4 on 2023-10-03 14:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mytrial", "0003_booking"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="booking_on",
            new_name="booked_on",
        ),
    ]
